In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
symbol_table = ["a", "b", "x", "y", "sum", "min"]
var_names = [1,2,3,4,5,6] 
sentences = [9.0603, 9.0604]
exprs = [3.0304]
main = [0.1,0.2,11.010205, 1.05, 0.3,0.4, 21.010102, 1.6]
target_gene = np.array(main + exprs + sentences)

In [3]:
target_gene

array([ 0.1     ,  0.2     , 11.010205,  1.05    ,  0.3     ,  0.4     ,
       21.010102,  1.6     ,  3.0304  ,  9.0603  ,  9.0604  ])

In [4]:
def interpret_expr(ex, symbols):
    # less than
    if str(ex).startswith("3."):
        frac = str(ex).split(".")[1]
        parts = frac.strip().split("0")
        return(symbols[int(parts[1])-1] + " < " + symbols[int(parts[2])-1] )

def interpret_stmnt(stmnt, symbols):
    # assignment
    if str(stmnt).startswith("9."):
        frac = str(stmnt).split(".")[1]
        parts = frac.strip().split("0")
        return("" + symbols[int(parts[1])-1] + " = " + symbols[int(parts[2])-1] )

def interpret(target, symbols, mainsize, exprsize):
    for i in range(mainsize):
        node = str(target[i])
        #input
        if node.startswith("0."):
            the_var=symbols[int(node.split(".")[1]) -1]
            print(""+the_var+ " = int.Parse(Console.ReadLine());")
        # output
        elif node.startswith("1."):
            the_var=symbols[int(node.split(".")[1]) -1]
            print("Console.WriteLine("+the_var+");")
        # addition statement
        elif node.startswith("11."):
            frac = node.split(".")[1]
            parts = frac.strip().split("0")
            print(symbols[int(parts[3])-1] +" = " + symbols[int(parts[1])-1] + " + " + symbols[int(parts[2])-1] +";")
        # if else statement
        elif node.startswith("21."):
            ifelse = node.split(".")[1]
            parts = ifelse.strip().split("0")
            #condition
            expr= (target [mainsize + int(parts[1]) -1])
            if_body = target [mainsize + exprsize + int(parts[1])-1 ]
            else_body = target [mainsize + exprsize + int(parts[2]) ]
            
            print("if ( " + interpret_expr(expr,symbols ) + " )")
            print("\t " + interpret_stmnt(if_body,symbols ) + " ;")
            print("else")
            print("\t " + interpret_stmnt(else_body,symbols ) + " ;")

In [5]:
interpret(target_gene, symbol_table, len(main), len(exprs))

a = int.Parse(Console.ReadLine());
b = int.Parse(Console.ReadLine());
sum = a + b;
Console.WriteLine(sum);
x = int.Parse(Console.ReadLine());
y = int.Parse(Console.ReadLine());
if ( x < y )
	 min = x ;
else
	 min = y ;
Console.WriteLine(min);


# Genotype
 - 15 numbers to create that face

In [6]:
target_gene

array([ 0.1     ,  0.2     , 11.010205,  1.05    ,  0.3     ,  0.4     ,
       21.010102,  1.6     ,  3.0304  ,  9.0603  ,  9.0604  ])

In [7]:
m = len(target_gene)
print(m)

11


In [8]:
def create_gene(M = m):
    return np.random.rand(m) * 10

In [9]:
my_gene = create_gene()
my_gene

array([7.39434982, 4.56418435, 4.71491331, 3.22669764, 9.40855565,
       6.91198229, 0.30578922, 7.06603527, 8.81956178, 9.4379009 ,
       7.22438908])

In [10]:
#interpret(my_gene, symbol_table, len(main), len(exprs))

# Fitness
 - How sucessful the gene of the agent
 - Euclidean Distance measures the error
 - similarity (fitness) is the inverse of distance
 
$$ Fitness(v) = \frac{1}{1 + dist(v, target)} $$
    

In [11]:
def fitness(v):
    error = (target_gene - v)
    return 1 / (1 + np.dot(error, error))

In [12]:
fitness(my_gene)

0.001353971330481525

In [13]:
fitness(target_gene)

1.0

# Population

In [14]:
N = 4
population = {i:create_gene() for i in range(N)}

In [15]:
population

{0: array([5.78849115, 3.76150704, 4.40412046, 2.989582  , 8.99934415,
        9.375933  , 0.91367724, 6.15234244, 5.12081951, 0.9319809 ,
        1.57459034]),
 1: array([9.51166646, 3.91787665, 5.52591476, 3.77439559, 0.65303144,
        4.67008523, 7.14310837, 9.19752136, 7.78963492, 6.85599168,
        8.3416246 ]),
 2: array([5.61984843, 6.41753452, 0.2514747 , 5.02263744, 8.31624748,
        7.35557431, 9.93317316, 0.29043832, 0.0259522 , 4.55666829,
        7.17111667]),
 3: array([1.72435121, 8.86972204, 9.33354705, 6.67664675, 5.03988878,
        4.20375096, 4.83869414, 5.792741  , 2.21168607, 0.81605688,
        6.230732  ])}

In [16]:
N = 10
population = {i:create_gene() for i in range(N)}

#fig = plt.figure()
#for i in range(10):
#    plt.subplot(2, 5, i+1)
#    draw_face(population[i])

# Selection
 - who are the successful agents

In [17]:
success = {agent_id: fitness(agent_genome) for agent_id, agent_genome in population.items()}

In [18]:
success

{0: 0.001705321224241095,
 1: 0.002222435490705757,
 2: 0.0020716696644444443,
 3: 0.0015467511944260047,
 4: 0.0019878813807209217,
 5: 0.001781237904129836,
 6: 0.0024074777359093646,
 7: 0.001550581148437278,
 8: 0.0015016157338796838,
 9: 0.00151632926806612}

In [19]:
total_success = sum(success.values())
total_success

0.018291300744960506

In [20]:
reproduction_probability = {agent_id: success[agent_id]/total_success for agent_id in success.keys()}

In [21]:
reproduction_probability

{0: 0.09323127141250101,
 1: 0.1215023207859106,
 2: 0.11325983282053992,
 3: 0.0845621214145831,
 4: 0.1086790605238181,
 5: 0.09738169684955787,
 6: 0.13161872791210086,
 7: 0.08477150805496889,
 8: 0.08209452978861542,
 9: 0.08289893043740416}

In [22]:
pr = [reproduction_probability[agent_id] for agent_id in range(N)]
select = np.random.choice(N, 2, replace= False, p=pr)
select

array([6, 2])

In [23]:
def selection(population):
    success = {agent_id: fitness(agent_genome) for agent_id, agent_genome in population.items()}
    total_success = sum(success.values())
    reproduction_probability = {agent_id: success[agent_id]/total_success for agent_id in success.keys()}
    pr = [reproduction_probability[agent_id] for agent_id in range(N)]
    select = np.random.choice(N, 2, replace= False, p=pr)
    return select

In [24]:
selection(population)

array([8, 2])

# Crossover

In [25]:
parent0 = population[select[0]]
parent1 = population[select[1]]

In [26]:
parent0

array([6.09095497, 9.09133731, 3.61564838, 2.61203008, 0.26448802,
       5.69960388, 8.18415864, 5.36572863, 7.14681204, 5.90394748,
       6.12345466])

In [27]:
parent1

array([7.39520326, 5.89464859, 1.86232157, 0.79353257, 1.19541945,
       8.40951944, 9.1530269 , 4.29353592, 7.17542132, 0.02112704,
       8.27523346])

In [28]:
cut = np.random.randint(m)

child0 = np.hstack((parent0[:cut],parent1[cut:]))
child1 = np.hstack((parent1[:cut],parent0[cut:]))

In [29]:
child0

array([6.09095497, 9.09133731, 1.86232157, 0.79353257, 1.19541945,
       8.40951944, 9.1530269 , 4.29353592, 7.17542132, 0.02112704,
       8.27523346])

In [30]:
child1

array([7.39520326, 5.89464859, 3.61564838, 2.61203008, 0.26448802,
       5.69960388, 8.18415864, 5.36572863, 7.14681204, 5.90394748,
       6.12345466])

In [31]:
def crossover(selectedParents):
    parent0 = population[selectedParents[0]]
    parent1 = population[selectedParents[1]]
    
    cut = np.random.randint(m)
    child0 = np.hstack((parent0[:cut],parent1[cut:]))
    child1 = np.hstack((parent1[:cut],parent0[cut:]))
    return child0, child1

In [32]:
crossover(select)

(array([6.09095497, 9.09133731, 3.61564838, 2.61203008, 0.26448802,
        5.69960388, 9.1530269 , 4.29353592, 7.17542132, 0.02112704,
        8.27523346]),
 array([7.39520326, 5.89464859, 1.86232157, 0.79353257, 1.19541945,
        8.40951944, 8.18415864, 5.36572863, 7.14681204, 5.90394748,
        6.12345466]))

# Mutation

In [33]:
def mutation(child, p = 0.05):
    mutation_point = np.random.randint(len(child))
    if np.random.rand() < p:
        child[mutation_point] = np.random.rand() * 10
    return child
    

In [34]:
mutation(child0, p = 0.995)

array([6.09095497, 9.09133731, 7.32446473, 0.79353257, 1.19541945,
       8.40951944, 9.1530269 , 4.29353592, 7.17542132, 0.02112704,
       8.27523346])